version: '3.8'

services:
  auth-service:
    build: ./backend/auth-service
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/authdb
      - PORT=5001
    depends_on:
      - mongo

  movie-service:
    build: ./backend/movie-service
    ports:
      - "5002:5002"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/moviedb
      - PORT=5002
    depends_on:
      - mongo

  user-service:
    build: ./backend/user-service
    ports:
      - "5003:5003"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/userdb
      - PORT=5003
    depends_on:
      - mongo

  gateway:
    build: ../backend/gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - user-service
      - movie-service

  client:
    build: ../client
    ports:
      - "3000:3000"
